export const ROOT_UID = "spm-19xx";

const somtimehta = ROOT_UID,
  bimlamehta = "bm-19xx",
  neerajmehta = "nm-19xx",
  sangeetamehta = "sg-19xx",
  rumamehta = "rm-198x",
  anoopramachandran = "an-198x",
  pranavramachandran = "pr-201x",
  devanshmehta = "dv-1989",
  rakshitamehta = "rk-199x",
  sanjeevkumarmehta = "skm-19xx",
  manishashubhramehta = "mm-19xx",
  kanikamehta = "km-1991",
  adityapushkarna = "ad-198x",
  adikapushkarna = "ad-2021",
  utkarshmehta = "um-1996",
  bhoorimehta = "bh-2020",
  damrumehta = "dm-2021",
  pradeepmehta = "pr-19xx",
  chandrikamehta = "ch-19xx",
  irikamehta = "ir-199x",
  ishitmehta = "is-1999",
  neetamehta = "ntm-19xx",
  ashoksharma = "as-19xx",
  akshaysharma = "ak-1992",
  niharikasharma = "nh-199x",
  arlosharma = "ar-201x",
  udishasharma = "ud-1997",
  manojmehta = "mn-19xx",
  manishamehta = "ma-19xx",
  gaurangmehta = "gu-2000",
  gaurimehta = "gu-200x",
  zaramehta = "zr-200x";

export const FAMILY = [
  {
    id: somtimehta,
    name: "Somti Prakash Mehta",
    sex: "M",
    status: "expired",
    DOB: "17 Jan, 19xx",
    DOD: "DD MMM, YYYY",
    marriedTo: bimlamehta,
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/somti_mehta_qFKO7z-kcU.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881479",
  },
  {
    id: bimlamehta,
    name: "Bimla Mehta",
    sex: "F",
    status: "active",
    DOB: "02 Feb, YYYY",
    marriedTo: somtimehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: neerajmehta,
    name: "Neeraj Mehta",
    childOf: [somtimehta, bimlamehta],
    sex: "M",
    status: "active",
    DOB: "10 Nov, 19xx",
    marriedTo: sangeetamehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: sangeetamehta,
    name: 'Sangeeta Mehta',
    sex: 'F',
    status: 'active',
    DOB: "16 Nov",
    marriedTo: neerajmehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: rumamehta,
    name: 'Ruma Mehta',
    sex: 'F',
    status: 'active',
    DOB: "13 Sep",
    marriedTo: anoopramachandran,
    childOf: [neerajmehta, sangeetamehta],
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: anoopramachandran,
    name: 'Anoop Ramachandran',
    sex: 'M',
    status: 'active',
    DOB: "23 Nov",
    marriedTo: rumamehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: pranavramachandran,
    name: 'Pranav Ramachandran',
    sex: 'M',
    status: 'active',
    DOB: "5 May",
    childOf: [rumamehta, anoopramachandran],
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/pranav_ramachandran_90T6YY41FZ.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881498",
  },
  {
    id: devanshmehta,
    name: 'Devansha Mehta',
    sex: 'M',
    status: 'active',
    DOB: "9 Dec",
    marriedTo: rakshitamehta,
    childOf: [neerajmehta, sangeetamehta],
    nickname: "Subhi",
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/devansh_mehta_RLOv5FfQb5.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881586",
  },
  {
    id: rakshitamehta,
    name: 'Rakshita Mehta',
    sex: 'F',
    status: 'active',
    DOB: "29 Sep",
    marriedTo: devanshmehta,
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/rakshita_mehta_flC8vH-cekc5.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881643",
  },
  {
    id: sanjeevkumarmehta,
    name: "Sanjeev Kumar Mehta",
    childOf: [somtimehta, bimlamehta],
    sex: "M",
    status: "active",
    DOB: "18 Aug, 19xx",
    marriedTo: manishashubhramehta,
    nickname: "Sanju",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: manishashubhramehta,
    name: "Manisha Mehta",
    sex: "F",
    status: "active",
    DOB: "15 Nov, 19xx",
    marriedTo: sanjeevkumarmehta,
    nickname: "Shubhra",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: kanikamehta,
    name: "Kanika Mehta",
    childOf: [sanjeevkumarmehta, manishashubhramehta],
    sex: "F",
    status: "active",
    DOB: "12 May, 1991",
    nickname: "Kanu",
    marriedTo: adityapushkarna,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: adityapushkarna,
    name: 'Aditya Pushkarna',
    sex: 'M',
    status: 'active',
    DOB: "17 May",
    marriedTo: kanikamehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: adikapushkarna,
    name: "Adika Pushkarna",
    childOf: [kanikamehta, adityapushkarna],
    sex: "F",
    status: "active",
    DOB: "13 Aug",
    nickname: "Bantu",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: utkarshmehta,
    name: "Utkarsh Mehta",
    childOf: [sanjeevkumarmehta, manishashubhramehta],
    sex: "M",
    status: "active",
    DOB: "5 Oct, 1996",
    nickname: "Kush",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: bhoorimehta,
    name: "Bhoori Mehta",
    childOf: [utkarshmehta],
    sex: "F",
    status: "expired",
    DOB: "5 Sept, 2020",
    DOD: "11 Oct, 2021",
    nickname: "Bhuru",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: damrumehta,
    name: "Damru Mehta",
    childOf: [utkarshmehta],
    sex: "M",
    status: "active",
    DOB: "1 Aug, 2021",
    nickname: "Babi",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: pradeepmehta,
    name: "Pradeep Mehta",
    childOf: [somtimehta, bimlamehta],
    sex: "M",
    status: "active",
    DOB: "11 Oct",
    marriedTo: chandrikamehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: chandrikamehta,
    name: "Chandrika Mehta",
    sex: "F",
    status: "active",
    DOB: "23 Sep",
    nickname: "Chinu",
    marriedTo: pradeepmehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: irikamehta,
    name: "Irika Mehta",
    childOf: [pradeepmehta, chandrikamehta],
    sex: "F",
    status: "active",
    DOB: "7 May",
    nickname: "Chinki",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: ishitmehta,
    name: "Ishit Mehta",
    childOf: [pradeepmehta, chandrikamehta],
    sex: "M",
    status: "active",
    DOB: "1 Mar",
    nickname: "Joey",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: neetamehta,
    name: "Neeta Sharma",
    childOf: [somtimehta, bimlamehta],
    sex: "F",
    status: "active",
    DOB: "DD MMM, 19xx",
    nickname: "Neetu",
    marriedTo: ashoksharma,
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/neeta_sharma_JpbC8EL_Du.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881487",
  },
  {
    id: ashoksharma,
    name: "Ashok Sharma",
    sex: "M",
    status: "active",
    DOB: "18 Apr",
    marriedTo: neetamehta,
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/ashok_sharma_i20L1GTbO.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881423",
  },
  {
    id: akshaysharma,
    name: "Akshay Sharma",
    childOf: [neetamehta, ashoksharma],
    sex: "M",
    status: "active",
    DOB: "17 Mar",
    nickname: "Krishan",
    marriedTo: niharikasharma,
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/akshay_sharma_jQLCHFlRE.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881493",
  },
  {
    id: niharikasharma,
    name: "Niharika Sharma",
    sex: "F",
    status: "active",
    DOB: "3 Sep",
    marriedTo: akshaysharma,
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/niharika_sharma_HsGODeIh7hC.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881508",
  },
  {
    id: arlosharma,
    name: "Arlo Shamra",
    childOf: [akshaysharma, niharikasharma],
    sex: "M",
    status: "active",
    DOB: "1 Sep",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: udishasharma,
    name: "Udisha Sharma",
    childOf: [neetamehta, ashoksharma],
    sex: "F",
    status: "active",
    DOB: "20 Oct",
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/udisha_sharma_RjaOEL1I5z.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881495",
  },
  {
    id: manojmehta,
    name: "Manoj Mehta",
    childOf: [somtimehta, bimlamehta],
    sex: "M",
    status: "active",
    DOB: "1 May",
    marriedTo: manishamehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: manishamehta,
    name: "Manisha Mehta",
    sex: "F",
    status: "active",
    DOB: "16 Sep",
    marriedTo: manojmehta,
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: gaurangmehta,
    name: "Gaurang Mehta",
    childOf: [manojmehta, manishamehta],
    sex: "M",
    status: "active",
    DOB: "20 May",
    nickname: "Gaurangi",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
  {
    id: gaurimehta,
    name: "Gauri Mehta",
    childOf: [manojmehta, manishamehta],
    sex: "F",
    status: "active",
    DOB: "25 Oct",
    nickname: "Gauru",
    photo: "https://ik.imagekit.io/bizwem110d/family-tree/gauri_mehta_oL8qLGbv0odK.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1642826881513",
  },
  {
    id: zaramehta,
    name: "Zara Mehta",
    childOf: [manojmehta, manishamehta],
    sex: "F",
    status: "active",
    DOB: "18 Jan",
    nickname: "Zorro",
    photo: "https://assets-itkkids-001.fra1.cdn.digitaloceanspaces.com/prabjyot/utkarsh.png",
  },
];

export const FindMember = (id) => {
  try {
    return FAMILY.find((mem) => mem.id === id);
  } catch {
    return {};
  }
};

export const FindParents = (id) => {
  try {
    return FAMILY.find((mem) => mem.id === id)["childOf"].map((parid) =>
      FAMILY.find((mem) => mem.id === parid)
    );
  } catch {
    return [];
  }
};

export const FindChildren = (parentid) => {
  try {
    return FAMILY.filter((mem) => "childOf" in mem).filter((mem) =>
      mem.childOf.includes(parentid)
    );
  } catch (err) {
    return [];
  }
};

export const FindCoupleChildren = (p1id, p2id) => {
  try {
    return FAMILY.filter((mem) => "childOf" in mem).filter((mem) =>
      mem.childOf.includes(p1id, p2id)
    );
  } catch {
    return [];
  }
};
